// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Monster : MonoBehaviour
{
	
	public float fun;
	public int level;
	private float charge;
	

	public void Start() {}

	public float getFun() {
		return fun;
	}

	public int getLevel() {
		return (int)(level * charge);
	}
	
	public void setCharge(float setCharge) {
		charge = setCharge;
	}
	
}


