// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class MonsterFactory
		{
				public MonsterFactory ()
				{
				}

				public Monster createSkeleton() {
					return Skeleton();
				}

				public Monster createOrc() {
					return Orc();
				}

				public Monster createDragon() {
					return Dragon();
				}

				public Monster createLich() {
					return Lich();
				}
		}
}

